### ISSUE TITLE
How to use functions

### ISSUE THREAD

**Issue by Alyeko** [chjch/pylusat#2]
Very helpful python package. Can you please provide some example code on how to use the functions of the package? Thanks

**Comment by chjch** [comment]
Hi @Alyeko, thanks for your request. I'm working on a documentation site for the package. Hopefully, it will be done in the next couple of weeks.

**Comment by Alyeko** [comment]
That's great, thanks!

**Comment by chjch** [comment]
@Alyeko As we are still in active development of PyLUSAT's documentation, please take a look at the current version of it on readthedocs at https://pylusat.readthedocs.io/.
